### ISSUE TITLE
createClass

### ISSUE THREAD

**Issue by stites** [bioball/mandolin#1]
Runs on http://ramdajs.com/0.17/docs - instanceof restricts the inputs such that they have to be instances. ie, with a  `var Foo = createClass({a: String})`, `Foo({a:new String("b")})` will run, but `Foo({a:"b"})` will not. Not exactly ideal.

You'd also want to look into using getters and setters instead of this simple assignment, so that you can verify types/instances.

```
function createClass (properties) {
  function Constructor (instantiatingObj){
     var _this = {}
     _this = R.mapObjIndexed(function (propertyclazz, property){
         var assignable = instantiatingObj[property]
         return assignable instanceof propertyclazz ? assignable.valueOf() : new Error("nice try");
     }, properties);
     return _this; // we could have shortened this to just a return of the R.map, but not today
  }
  return Constructor
}
```

**Comment by bioball** [comment]
Ok, I just implemented my own version, check it out. I'm trying to avoid depending on a library here, so I ended up writing my own `mapObj` and `extend` to implement this.

A note about your implementation--invoking a function with `new` ignores the return value of your function, so your although your impl might work, I believe can't be called using `new`.

**Comment by bioball** [comment]
I'm really surprised that `"foo" instanceof String` is false. I see what you mean by getters/setters. I'll have to think about this some more.

**Comment by stites** [comment]
yeah, it's because they're unboxed - you may wind up needing two checks. One for primitives and one for prototypal inheritance. Closing this ticket since it was only intended to be a one-off reference!
